apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-website
  template:
    metadata:
      labels:
        app: coffee-website
    spec:
      containers:
        - name: coffee-website-container
          image: aftab2010/coffee-website
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-website-service
spec:
  selector:
    app: coffee-website
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30001